branches:
  - master
  - feature/travis
  - feature/travis-test

sudo: required
dist: trusty

addons:
  apt:
    sources:
      - sourceline: 'deb https://debian.neo4j.org/repo stable/'
        key_url: 'https://debian.neo4j.org/neotechnology.gpg.key'
    packages:
      - neo4j

language: node_js

node_js:
  - "stable"

services:
  - mongodb
  # - neo4j

# before_install:
#   - >
#     curl -H "Content-Type: application/json" -X POST -d '{"password":"admin"}' -u neo4j:neo4j http://localhost:7474/user/neo4j/password

before_script:
  - sleep 15

after_succes:
  - npm run coveralls

deploy:
  provider: heroku
  api_key:
    secure: process.env.HEROKU_API_KEY
  app: sportuniteb3-angular
